#mobile=7800515152
mobile=7030704455
name=Aksh
email=aks.01@yahoo.com
#testname=healthians gym male package 
testname=Amino Acid Qualitative screen, Urine

number_of_members=
url=https://webd003.healthians.co.in
city=gurgaon
awsdburl=jdbc:mysql://devdb002.crljpighpbvc.ap-south-1.rds.amazonaws.com:3306/d10
dburl=jdbc:mysql://gateway.echl.in:10302/d10
dbuser=akshay_mankar
dbpassword=uLew5RIaxrvbsF36yL6oIpvD
otpretries=3
otpinterval=500
browser=remote
remoteUrl=http://localhost:4444/wd/hub